name: "Consumed container workflow"

on:
  push:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 7 * * 1'

jobs:
  call-reusable-container:
    uses: pritchyspritch/reusable-workflows/.github/workflows/reusable-container-workflow.yml@main
    with:
      docker-path: './Dockerfile-path' # Set path to Dockerfile
